### PR TITLE
Muplile fixes: black border, change Whonix DispVM browser, fix sys-net trust color

### PR DESCRIPTION
**Pull request by deeplow**
Per request of @andrewdavidwong https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-687687411

changes included:
  - PNG with transparent background
  - made white background for hardware rectangles and disk
  - made AppVM 3's title font match other VMs
  - (**edit**) AppVM 3 (whonix based) now has Tor Browser instead of Firefox
  - (**edit**) sys-net color and associated networking hardware are now considered untrusted (red)

qubes-trust-level-architecture

### CODE REVIEW

**Comment by deeplow** [comment]
(force push was to remove a tiny imperfection in the hardware boxes corner. It was making a sharp white background instead of a rounded one.

**Comment by deeplow** [comment]
I think by default draw.io saves this as compressed XML. I'll fix this later.

**Edit:** fixed

**Comment by deeplow** [comment]
Some new changes.

### Sys-net color to red

Following https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-688117888, I have changed the color of sys-net to red and the related hardware as well as the connection from it to sys-firewall (not sure)

| Before | After |
|----------|--------|
|sys-net_before |sys-net|


### Whonix DispVM browser change

Following https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-687813237 I have change the shown browser in whonix DispVM (AppVM 3) to Tor Browser instead of Firefox

|Before | After|
|---------|-------|
|firefox| torbb|

**Comment by deeplow** [comment]
### Sys-net --- Sys-firewall (edge) is now green

Following https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-688527462, I have changed the color of sys-net to red and the related hardware as well as the connection from it to sys-firewall (not sure)

| Before | After |
|----------|--------|
|sys-net|new-edge|

### Whonix color
Following https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-688518820 I have changed the sys-whonix color to black

|Before | After|
|---------|-------|
|whonix_old | whonix_new |

**Comment by deeplow** [comment]
## Making GUI VM and Template Trusted
Implemented changes stated in https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-688677518

qubes-trust-level-architecture_proposal

**Comment by fepitre** [comment]
This looks very nice. Are we good with latest changes?

**Comment by deeplow** [comment]
Thanks! Just [two final points](https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-689557955) to polish and after that I think it's ready.

**Comment by deeplow** [comment]
Keyboard added to sys-usb attached devices. 

qubes-trust-level-architecture

**Comment by deeplow** [comment]
@fepitre It's [ready to merge](https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-691617368). Thanks for reviewing it!

**Pull request merged**
