### PR TITLE
add trust level architecture diagram

### PR DESCRIPTION
**Pull request by deeplow**
Reconstructed from the one available in https://qubes-os.org/intro/

Some minor tweaks to the original:
  - replaced wifi card with ethernet jack (more recognizable)
  - Fixed typo: there were two appVMs name "AppVM 2"
  - replaced logo on the left of AppVM 1 (couldn't recognize) with Thunderbird logo
  - centered text on sys-* qubes and AdminVM, GUI VM

### CODE REVIEW

**Comment by fepitre** [comment]
@deeplow thank you. what about this comment: https://qubes-os.discourse.group/t/suggestions-for-qubes-architecture-diagram/377/11?u=fepitre
I think it makes sense.

**Comment by deeplow** [comment]
> I think it makes sense.

@fepitre Yes, let's add those changes. I just wanted to check out with you if the base version (with the listed modifications is fine)

I'll push another commit with said changes

**Comment by deeplow** [comment]
Had to force-push these changes because 2Mb commits don't forgive (I think it's because of all the images). Do you want me to try to compress them? @fepitre 

(some other commits were just fixing tiny imperfections like micro alignments and adding a 3px transparent border to the PNG). Here's how it looks:

qubes-trust-level-architecture

I also wanted to do some tweaks (in styling) that I'd like to propose but maybe that should be as a separate PR. What do you think? (they are things like reducing the roundness of the border, changing slightly the grey "levels of trust" bar)

**Comment by deeplow** [comment]
Opened up an issue to track this: https://github.com/QubesOS/qubes-issues/issues/6034

**Comment by fepitre** [comment]
> Had to force-push these changes because 2Mb commits don't forgive (I think it's because of all the images). Do you want me to try to compress them? @fepitre

Well I think we can keep them as is. Generally I prefer to keep the best quality/quantity of information in the source then the compression is done at the rendered image.

> I also wanted to do some tweaks (in styling) that I'd like to propose but maybe that should be as a separate PR. What do you think? (they are things like reducing the roundness of the border, changing slightly the grey "levels of trust" bar)

Yes please another PR. Also, maybe it is worth to have common pattern in all XML to represent VM etc. So if you want to change default shape do you mind to adapt also in others?

Also, could you upload uncompressed XML please? it's easier for crazy dudes like me to edit the XML manually. BTW, I'm currently thinking on a way for providing a script using drawio cli to render the images. If you have some time on the subject, that would be welcomed.

**Comment by deeplow** [comment]
> Well I think we can keep them as is. Generally I prefer to keep the best quality/quantity of information in the source then the compression is done at the rendered image.

:+1: Ok. Let's go with that.

> Also, could you upload uncompressed XML please? it's easier for crazy dudes like me to edit the XML manually.

Of course!

> So if you want to change default shape do you mind to adapt also in others?

I'm not to familiar with XML but I may take a look at this. Do you have any good pointers on how to do this. Also, what's your workflow for editing these XML files?

> BTW, I'm currently thinking on a way for providing a script using drawio cli to render the images.

Hum. I'm not sure [it's worth the time](https://xkcd.com/1205/) to automate. Where would the script render them to?
Also, do you mean [this](https://github.com/rlespinasse/drawio-cli) docker-based drawio-cli?

**Comment by fepitre** [comment]
> I'm not to familiar with XML but I may take a look at this. Do you have any good pointers on how to do this. Also, what's your workflow for editing these XML files?

Currently I'm just importing them into draw.io and do the suff but if I want to change only the text, I just open VIM.
 
> > BTW, I'm currently thinking on a way for providing a script using drawio cli to render the images.
> 
> Hum. I'm not sure [it's worth the time](https://xkcd.com/1205/) to automate. Where would the script render them to?
> Also, do you mean [this](https://github.com/rlespinasse/drawio-cli) docker-based drawio-cli?

Few months ago I used drawio-desktop where, if my memory is correct, there is a cli tool to render directly the XML. But well, I'm mostly using the drawio webui for rendering the images currently. It's very manual procedure (I don't like that). Such script can be useful when you want to include generated images into Latex/Beamer/Markdown etc and where you have a big Makefile doing the job for you :D.

**Comment by deeplow** [comment]
> Such script can be useful when you want to include generated images into Latex/Beamer/Markdown etc and where you have a big Makefile doing the job for you :D.

Haha. I see :D I'll pass on the opportunity for now, though. I also don't like all the manual process, but I can stand it for now. When it becomes too much of a pain-point I'll look into that!

Also, the PR is ready (I think). And btw, what's the name of that app I replaced with thunderbird?

**Comment by fepitre** [comment]
> Also, the PR is ready (I think). And btw, what's the name of that app I replaced with thunderbird?
No idea...

**Comment by fepitre** [comment]
Thank you again.

**Pull request merged**
